### PR TITLE
First commits

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request contains the first commits for this new Ansible role.

## 💭 Motivation and context ##

We should prepare for integration with Okta.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
This PR's GitHub Actions checks should pass once the changes from Lineage trickle down.

**Review by dav3r — APPROVED** [review]
LGTM! 🐙

**Review by jasonodoom — APPROVED** [review]
LGTM! Though I am not too happy with the  PR name. Don't we usually opt for something more descriptive?

**Comment by jsf9k** [comment]
> LGTM! Though I am not too happy with the PR name. Don't we usually opt for something more descriptive?

This is the usual name we use for the PR that creates the first commits for a repo after starting from a skeleton.

**Pull request merged**
